name = "ML Imagenet Postprocessor"
language = "rust"
type = "actor"
version = "0.2.0"

[actor]
claims = ["wasmcloud:imagenet", "wasmcloud:builtin:logging"]
call_alias = "mlinference/imagenetpostprocessor"
